[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && npm install --include=dev --prefix client && npm run build --prefix client"

[deploy]
startCommand = "node server/index.js"
