-- ─── Migration 193 — Fix TT-Proturf account number ───────────────────────────
--
-- TT-Proturf was created via the AI onboarding flow and the requested account
-- number (MOOV-0183) was not honoured — the sequence had already advanced to
-- 237 so the auto-generate trigger assigned MOOV-0238 instead.
--
-- Root cause: both POST /customers and POST /api/customers/ai-onboard did not
-- accept an account_number parameter — it was always auto-generated by the
-- trigger. Fixed in this deploy: both endpoints now accept an optional
-- account_number field that, when supplied, is passed in the INSERT so the
-- trigger (which only fires when account_number IS NULL) leaves it alone.
--
-- This migration corrects the specific wrong value already in production.

UPDATE customers
SET    account_number = 'MOOV-0183'
WHERE  business_name ILIKE '%proturf%'
  AND  account_number = 'MOOV-0238';
