-- Migration 286: AI email response learning layer
--
-- Powers the AI-draft → human-review → learn feedback loop.
--
-- Flow:
--   1. Inbound email arrives → classified by fast model (Haiku/Flash)
--   2. Draft generated by capable model (Sonnet) → stored in ai_response_drafts
--   3. Staff approves / edits / rejects / refines → stored in ai_response_feedback
--   4. Background job extracts patterns from feedback → ai_style_patterns
--   5. ai_automation_rules controls per-group stage (supervised/assisted/autonomous)
--
-- ai_response_drafts     — every AI-generated draft with full generation context
-- ai_response_feedback   — what the human did (approve/edit/reject/refine)
-- ai_style_patterns      — learned style rules injected into future prompts
-- ai_automation_rules    — per-group automation stage and graduation thresholds

BEGIN;

-- ── 1. ai_response_drafts ──────────────────────────────────────────────────────
-- One row per AI draft. Stores the full context that was passed to the model
-- so we can reproduce, audit, and compare drafts over time.

CREATE TABLE IF NOT EXISTS ai_response_drafts (
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  query_id              UUID          NOT NULL REFERENCES queries(id) ON DELETE CASCADE,

  -- Model used
  model_provider        VARCHAR(20)   NOT NULL DEFAULT 'anthropic',
    -- 'anthropic' | 'google'
  model_name            VARCHAR(60)   NOT NULL,
    -- e.g. 'claude-haiku-4-5', 'claude-sonnet-4-6', 'gemini-2.0-flash'
  prompt_version        INTEGER       NOT NULL DEFAULT 1,
    -- increments when the system prompt template changes — lets us A/B compare

  -- Classification output (from fast model, step 1)
  intent                VARCHAR(50),
    -- missing_parcel | damage_claim | delay | failed_delivery | billing | general
  intent_confidence     NUMERIC(4,3),
    -- 0.000 – 1.000
  entities_extracted    JSONB,
    -- { tracking_number, courier_code, claim_type, urgency, sentiment }
  urgency               VARCHAR(20)   DEFAULT 'normal',
    -- low | normal | high | urgent

  -- Generation context (what was passed to the drafting model)
  generation_context    JSONB,
    -- { thread_summary, customer_name, parcel_status, courier_config,
    --   style_patterns_used: [...], example_ids_used: [...] }

  -- The draft
  draft_text            TEXT          NOT NULL,
  draft_subject         VARCHAR(500),

  -- Cost tracking
  tokens_input          INTEGER,
  tokens_output         INTEGER,
  cost_pence            NUMERIC(8,4),

  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_drafts_query   ON ai_response_drafts(query_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_drafts_intent  ON ai_response_drafts(intent, intent_confidence);

COMMENT ON COLUMN ai_response_drafts.prompt_version IS
  'Increments when the system prompt template changes. Use to compare draft quality across prompt versions.';
COMMENT ON COLUMN ai_response_drafts.generation_context IS
  'Full context passed to the model. Includes style_patterns_used[] and example_ids_used[] so we know exactly why this draft was generated this way.';


-- ── 2. ai_response_feedback ───────────────────────────────────────────────────
-- One row per human action on a draft.
-- This is the primary training signal — the diff between draft_text and
-- sent_text is what the model learns from.

CREATE TABLE IF NOT EXISTS ai_response_feedback (
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_id              UUID          NOT NULL REFERENCES ai_response_drafts(id) ON DELETE CASCADE,
  query_id              UUID          NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
  staff_id              UUID          REFERENCES staff(id) ON DELETE SET NULL,

  -- What happened
  action                VARCHAR(20)   NOT NULL,
    -- approved    — sent exactly as drafted (strong positive signal)
    -- edited      — staff edited before sending (diff = training signal)
    -- refined     — staff used refinement prompt to rewrite (prompt = signal)
    -- rejected    — discarded, staff wrote from scratch (negative signal)

  -- The text that was actually sent (NULL if rejected / not sent)
  sent_text             TEXT,

  -- If action = 'refined': the prompt the staff member typed
  refinement_prompt     TEXT,
    -- e.g. "be more apologetic about the delay" or "mention the 28-day deadline"

  -- Structured diff between draft and sent (populated by application layer)
  -- Schema: { added: [...], removed: [...], changed_phrases: [{from, to}] }
  edit_diff             JSONB,

  -- Whether this was sent without human review (auto-send in assisted/autonomous)
  was_auto_sent         BOOLEAN       NOT NULL DEFAULT FALSE,

  -- Outcome tracking (filled in later, e.g. by AI or staff marking the query resolved)
  customer_replied      BOOLEAN,
  resolved_after_send   BOOLEAN,

  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_feedback_draft   ON ai_response_feedback(draft_id);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_query   ON ai_response_feedback(query_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_action  ON ai_response_feedback(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_staff   ON ai_response_feedback(staff_id, action);

COMMENT ON COLUMN ai_response_feedback.edit_diff IS
  'Structured diff between ai draft and sent text. Populated by the app layer after send. Used by the background pattern-extraction job to build ai_style_patterns.';


-- ── 3. ai_style_patterns ──────────────────────────────────────────────────────
-- Distilled rules extracted from feedback, injected into future generation prompts.
-- Populated and updated by a periodic background job (not by the user directly).
-- The staff can review and deactivate patterns via the AI settings screen.

CREATE TABLE IF NOT EXISTS ai_style_patterns (
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  pattern_type          VARCHAR(30)   NOT NULL,
    -- tone          — voice/register adjustments ("always sound empathetic, not robotic")
    -- phrase        — specific phrase replacements ("use 'we' not 'I'")
    -- always_include — elements that must appear ("always state the claim deadline date")
    -- never_include  — things to omit ("never say 'unfortunately' as the first word")
    -- scenario      — full example pair for a specific situation

  -- Scope — NULL means applies to all groups/intents
  group_name            VARCHAR(50),
    -- NULL | 'Claims' | 'Queries' | 'Billing' | 'Technical'
  intent                VARCHAR(50),
    -- NULL | 'missing_parcel' | 'damage_claim' | 'delay' | etc.

  -- The rule
  pattern_description   TEXT          NOT NULL,
    -- Human-readable rule injected into the system prompt
    -- e.g. "When a customer mentions they are close to a deadline, always acknowledge
    --       the specific deadline date and confirm the next action step."

  -- Optional before/after example (shown in UI and included in prompt when relevant)
  example_before        TEXT,
  example_after         TEXT,

  -- Provenance
  source_feedback_ids   UUID[]        NOT NULL DEFAULT '{}',
    -- Which ai_response_feedback rows led to this pattern
  occurrence_count      INTEGER       NOT NULL DEFAULT 1,
    -- How many feedback records exhibit this pattern

  -- Quality signal
  confidence_score      NUMERIC(4,3)  NOT NULL DEFAULT 0.5,
    -- Rises as more feedback confirms the pattern, falls if staff deactivate it

  is_active             BOOLEAN       NOT NULL DEFAULT TRUE,
  is_auto_generated     BOOLEAN       NOT NULL DEFAULT TRUE,
    -- FALSE = manually written by staff in settings

  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_patterns_active  ON ai_style_patterns(is_active, group_name, intent);
CREATE INDEX IF NOT EXISTS idx_ai_patterns_type    ON ai_style_patterns(pattern_type, confidence_score DESC);

COMMENT ON TABLE ai_style_patterns IS
  'Distilled style rules extracted from staff edits. Injected into the generation prompt as a dynamic "style guide" so the model evolves without fine-tuning.';


-- ── 4. ai_automation_rules ────────────────────────────────────────────────────
-- Controls per-group automation stage and graduation thresholds.
-- One row per group. The application checks this before deciding whether to
-- auto-send or queue for review.

CREATE TABLE IF NOT EXISTS ai_automation_rules (
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  group_name            VARCHAR(50)   NOT NULL UNIQUE,
    -- 'Claims' | 'Queries' | 'Billing' | 'Technical'

  -- Current stage
  automation_stage      VARCHAR(20)   NOT NULL DEFAULT 'supervised',
    -- supervised  — AI drafts, human approves everything before send
    -- assisted    — AI auto-sends high-confidence simple cases; flags ambiguous ones
    -- autonomous  — AI handles full thread; human can intervene at any time

  -- Thresholds for auto-send in assisted/autonomous
  confidence_threshold  NUMERIC(4,3)  NOT NULL DEFAULT 0.850,
    -- Minimum intent_confidence required to auto-send (assisted/autonomous only)
  approval_rate_threshold NUMERIC(4,3) NOT NULL DEFAULT 0.920,
    -- Rolling approval rate required before graduation to next stage is offered

  -- Rolling window for approval rate calculation
  approval_window_days  INTEGER       NOT NULL DEFAULT 30,

  -- Cached stats (recalculated nightly)
  current_approval_rate NUMERIC(4,3),
  total_drafts_30d      INTEGER       NOT NULL DEFAULT 0,
  auto_sent_30d         INTEGER       NOT NULL DEFAULT 0,
  human_edited_30d      INTEGER       NOT NULL DEFAULT 0,
  human_rejected_30d    INTEGER       NOT NULL DEFAULT 0,

  -- Emergency pause (overrides stage — no auto-sends)
  paused                BOOLEAN       NOT NULL DEFAULT FALSE,
  paused_reason         TEXT,
  paused_by             UUID          REFERENCES staff(id) ON DELETE SET NULL,
  paused_at             TIMESTAMPTZ,

  -- Audit
  stage_changed_by      UUID          REFERENCES staff(id) ON DELETE SET NULL,
  stage_changed_at      TIMESTAMPTZ,

  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Seed one row per group — all start in supervised mode
INSERT INTO ai_automation_rules (group_name, automation_stage) VALUES
  ('Claims',    'supervised'),
  ('Queries',   'supervised'),
  ('Billing',   'supervised'),
  ('Technical', 'supervised')
ON CONFLICT (group_name) DO NOTHING;

COMMIT;

DO $$
BEGIN
  RAISE NOTICE 'Migration 286 complete — AI learning layer tables created: ai_response_drafts, ai_response_feedback, ai_style_patterns, ai_automation_rules. All groups seeded in supervised mode.';
END $$;
