-- ──────────────────────────────────────────────────────────────────
-- 313 — Onboarding Engine
--
-- Replaces the manual ClickUp / spreadsheet onboarding workflow with a
-- first-class Kanban pipeline inside Moov OS.
--
-- Object model (split per the product spec):
--   1. onboarding_customers   — Metadata + Company Profile + Sales Integration
--   2. onboarding_addresses   — Trading & Billing addresses (one row per type)
--   3. onboarding_contacts    — Primary / Billing / Operational leads
--   4. onboarding_interactions— Inbound/outbound interaction log + media assets
--   5. onboarding_sla_targets — Per-status SLA duration (hours)
--
-- Custom string ID:  Moov-01, Moov-02 … Moov-124, Moov-125
--   Generated by a dedicated sequence + BEFORE INSERT trigger.
--   NB: distinct from the queries ticket sequence (MOOV-001) — different
--       prefix casing and a separate sequence so the two never collide.
-- ──────────────────────────────────────────────────────────────────

-- ─── 1. Enums ───────────────────────────────────────────────────────
-- Kanban pipeline statuses, in pipeline order.
DO $$ BEGIN
  CREATE TYPE onboarding_status AS ENUM (
    'verification',
    'carrier_provisioning',
    'tech_integration',
    'hardware_checklist',
    'go_live_ready'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Address purpose.
DO $$ BEGIN
  CREATE TYPE onboarding_address_type AS ENUM ('trading', 'billing');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Contact role on the account.
DO $$ BEGIN
  CREATE TYPE onboarding_contact_role AS ENUM ('primary_onboarding', 'billing', 'operational');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Who authored an interaction / sent the last reply.
DO $$ BEGIN
  CREATE TYPE onboarding_party AS ENUM ('client', 'team', 'carrier');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Direct Debit set-up choice.
DO $$ BEGIN
  CREATE TYPE onboarding_dd_choice AS ENUM ('direct_debit', 'bacs', 'card', 'invoice_30_days', 'none');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Rate-file lifecycle.
DO $$ BEGIN
  CREATE TYPE onboarding_rate_file_status AS ENUM ('not_received', 'received', 'in_review', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── 2. Custom Moov-XX sequence ─────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS onboarding_moov_seq START 1;

-- ─── 3. Core table: onboarding_customers ────────────────────────────
CREATE TABLE IF NOT EXISTS onboarding_customers (
  -- ── Metadata ──────────────────────────────────────────────────────
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  moov_id               TEXT UNIQUE,                       -- 'Moov-01' (auto-assigned by trigger)
  status                onboarding_status NOT NULL DEFAULT 'verification',
  -- Linkage to the live customer record once go-live completes (nullable until then)
  customer_id           UUID REFERENCES customers(id) ON DELETE SET NULL,

  -- ── SLA tracking ──────────────────────────────────────────────────
  status_entered_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- when current status began
  sla_due_at            TIMESTAMPTZ,                        -- deadline for current status
  last_reply_at         TIMESTAMPTZ,                        -- "Last Reply" metric
  last_reply_by         onboarding_party,                   -- client / team / carrier
  is_archived           BOOLEAN NOT NULL DEFAULT FALSE,

  -- ── Company profile ───────────────────────────────────────────────
  legal_name            TEXT NOT NULL,
  trading_name          TEXT,
  vat_number            TEXT,
  company_reg_number    TEXT,
  website               TEXT,
  primary_email         TEXT,
  primary_phone         TEXT,

  -- ── Sales integration metadata ────────────────────────────────────
  carrier_choices       JSONB NOT NULL DEFAULT '[]'::jsonb, -- e.g. ["dpd","royal_mail","dhl"]
  dd_choice             onboarding_dd_choice NOT NULL DEFAULT 'none',
  dd_reference          TEXT,                               -- mandate ref once set up
  rate_file_status      onboarding_rate_file_status NOT NULL DEFAULT 'not_received',
  rate_file_url         TEXT,
  rate_file_received_at TIMESTAMPTZ,
  salesperson_id        UUID REFERENCES staff(id) ON DELETE SET NULL,
  owner_id              UUID REFERENCES staff(id) ON DELETE SET NULL, -- onboarding owner

  -- ── Free-form pipeline state ──────────────────────────────────────
  active_action_item    TEXT,                               -- shown on the card
  source_payload        JSONB,                              -- raw inbound form webhook
  notes                 TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_customers_status   ON onboarding_customers (status) WHERE is_archived = FALSE;
CREATE INDEX IF NOT EXISTS idx_onboarding_customers_moov_id  ON onboarding_customers (moov_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_customers_sla_due  ON onboarding_customers (sla_due_at) WHERE is_archived = FALSE;

-- ─── 4. Addresses (trading + billing) ───────────────────────────────
CREATE TABLE IF NOT EXISTS onboarding_addresses (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  onboarding_id UUID NOT NULL REFERENCES onboarding_customers(id) ON DELETE CASCADE,
  address_type  onboarding_address_type NOT NULL,
  line1         TEXT,
  line2         TEXT,
  city          TEXT,
  county        TEXT,
  postcode      TEXT,
  country       TEXT NOT NULL DEFAULT 'United Kingdom',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- One trading + one billing address per onboarding record
  UNIQUE (onboarding_id, address_type)
);

CREATE INDEX IF NOT EXISTS idx_onboarding_addresses_record ON onboarding_addresses (onboarding_id);

-- ─── 5. Contacts (primary / billing / operational) ──────────────────
CREATE TABLE IF NOT EXISTS onboarding_contacts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  onboarding_id UUID NOT NULL REFERENCES onboarding_customers(id) ON DELETE CASCADE,
  role          onboarding_contact_role NOT NULL,
  full_name     TEXT,
  job_title     TEXT,
  email         TEXT,
  phone         TEXT,
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- One distinct contact record per role per onboarding record
  UNIQUE (onboarding_id, role)
);

CREATE INDEX IF NOT EXISTS idx_onboarding_contacts_record ON onboarding_contacts (onboarding_id);

-- ─── 6. Interaction log (+ media assets) ────────────────────────────
CREATE TABLE IF NOT EXISTS onboarding_interactions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  onboarding_id UUID NOT NULL REFERENCES onboarding_customers(id) ON DELETE CASCADE,
  sender        onboarding_party NOT NULL,           -- client / team / carrier
  channel       TEXT NOT NULL DEFAULT 'email',        -- email / note / system
  subject       TEXT,
  body          TEXT,
  media_assets  JSONB NOT NULL DEFAULT '[]'::jsonb,   -- [{ filename, url, content_type, size }]
  external_id   TEXT,                                 -- provider message id (dedupe)
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_interactions_record ON onboarding_interactions (onboarding_id, occurred_at DESC);

-- ─── 7. SLA targets per status (hours) ──────────────────────────────
CREATE TABLE IF NOT EXISTS onboarding_sla_targets (
  status          onboarding_status PRIMARY KEY,
  duration_hours  INT NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sensible defaults (working-hours-ish targets; tune in the UI later).
INSERT INTO onboarding_sla_targets (status, duration_hours) VALUES
  ('verification',          24),
  ('carrier_provisioning',  72),
  ('tech_integration',      96),
  ('hardware_checklist',    48),
  ('go_live_ready',         24)
ON CONFLICT (status) DO NOTHING;

-- ─── 8. Trigger: auto-assign Moov-XX on insert ──────────────────────
CREATE OR REPLACE FUNCTION assign_onboarding_moov_id()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  seq_val BIGINT;
BEGIN
  IF NEW.moov_id IS NULL THEN
    seq_val      := nextval('onboarding_moov_seq');
    -- LPAD to a minimum of 2 digits: Moov-01 … Moov-99, then naturally Moov-100+
    NEW.moov_id  := 'Moov-' || LPAD(seq_val::TEXT, 2, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_onboarding_moov_id ON onboarding_customers;
CREATE TRIGGER trg_onboarding_moov_id
  BEFORE INSERT ON onboarding_customers
  FOR EACH ROW EXECUTE FUNCTION assign_onboarding_moov_id();

-- ─── 9. Trigger: keep updated_at fresh ──────────────────────────────
CREATE OR REPLACE FUNCTION touch_onboarding_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_onboarding_customers_touch ON onboarding_customers;
CREATE TRIGGER trg_onboarding_customers_touch
  BEFORE UPDATE ON onboarding_customers
  FOR EACH ROW EXECUTE FUNCTION touch_onboarding_updated_at();
