// Auto-generated from Voila API — courier key → thumbnail URL
// Matches on courier_code (case-insensitive)
const COURIER_LOGOS = {
  "AGL": "https://app.heyvoila.io/courier-service-logos/thumbnails/AGL-Logo.png",
  "AIT": "https://app.heyvoila.io/courier-service-logos/thumbnails/ait.jpg",
  "AJPCouriers": "https://app.heyvoila.io/courier-service-logos/thumbnails/ajpcouriers.jpg",
  "AKMGlobal": "https://app.heyvoila.io/courier-service-logos/thumbnails/akm.jpg",
  "AKMGlobalSolutions": "https://app.heyvoila.io/courier-service-logos/thumbnails/akm.jpg",
  "AltLogic": "https://app.heyvoila.io/courier-service-logos/thumbnails/altlogic.jpg",
  "Amazon": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon.jpg",
  "AmazonEasyShip": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon-shipping.jpg",
  "AmazonShippingCentral": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon-shipping.jpg",
  "AmazonFrance": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon-shipping.jpg",
  "AmazonItaly": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon-shipping.jpg",
  "AmazonSpain": "https://app.heyvoila.io/courier-service-logos/thumbnails/amazon-shipping.jpg",
  "AnPost": "https://app.heyvoila.io/courier-service-logos/thumbnails/an-post.jpg",
  "APC": "https://app.heyvoila.io/courier-service-logos/thumbnails/apc.jpg",
  "APGGlobal": "https://app.heyvoila.io/courier-service-logos/thumbnails/apgglobal.jpg",
  "ArrowXL": "https://app.heyvoila.io/courier-service-logos/thumbnails/arrowxl.jpg",
  "Asendia": "https://app.heyvoila.io/courier-service-logos/thumbnails/asendia.jpg",
  "B2CEurope": "https://app.heyvoila.io/courier-service-logos/thumbnails/b2c.jpg",
  "BarcodeLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/barcodelogistics.jpg",
  "BirdSystem": "https://app.heyvoila.io/courier-service-logos/thumbnails/bird-system.jpg",
  "BJS": "https://app.heyvoila.io/courier-service-logos/thumbnails/bjshomedelivery.jpg",
  "BoxedoffBarcodes": "https://app.heyvoila.io/courier-service-logos/thumbnails/boxedoff.jpg",
  "BulletExpress": "https://app.heyvoila.io/courier-service-logos/thumbnails/bullet-express.jpeg",
  "Caribou": "https://app.heyvoila.io/courier-service-logos/thumbnails/caribou.jpg",
  "Chronopost": "https://app.heyvoila.io/courier-service-logos/thumbnails/chronopost.jpg",
  "CitySprint": "https://app.heyvoila.io/courier-service-logos/thumbnails/citysprint.jpg",
  "ColisPriveFR": "https://app.heyvoila.io/courier-service-logos/thumbnails/colisprive.png",
  "Coll8": "https://app.heyvoila.io/courier-service-logos/thumbnails/coll8.jpg",
  "CollectPlus": "https://app.heyvoila.io/courier-service-logos/thumbnails/collectplus.jpg",
  "Correos": "https://app.heyvoila.io/courier-service-logos/thumbnails/correos.jpg",
  "CRTransport": "https://app.heyvoila.io/courier-service-logos/thumbnails/cr-transport.jpg",
  "CSM": "https://app.heyvoila.io/courier-service-logos/thumbnails/csm.jpg",
  "Dachser": "https://app.heyvoila.io/courier-service-logos/thumbnails/dachser.jpg",
  "DaiPost": "https://app.heyvoila.io/courier-service-logos/thumbnails/daipost.jpg",
  "Deliver360": "https://app.heyvoila.io/courier-service-logos/thumbnails/deliver-360.jpg",
  "Deliver365": "https://app.heyvoila.io/courier-service-logos/thumbnails/deliver365.jpg",
  "Delnext": "https://app.heyvoila.io/courier-service-logos/thumbnails/delnext.jpg",
  "DeutschePost": "https://app.heyvoila.io/courier-service-logos/thumbnails/deutschepost.jpg",
  "DHLeCommerce": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-ecommerce.jpg",
  "DHL": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl.jpg",
  "DHLParcelDE": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DHLParcelNL": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DHLParcelSpain": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DHLParcelUK": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DHLPoland": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DHLWarenpost": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-warren.jpg",
  "DHLParcelUKCloud": "https://app.heyvoila.io/courier-service-logos/thumbnails/dhl-parcel.jpg",
  "DPD": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd.jpg",
  "DPDAustria": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd-austria.jpg",
  "DPDC2C": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd.jpg",
  "DPDGermany": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd.jpg",
  "DPDIreland": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd-ireland.jpg",
  "DPDLocal": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpdlocal.jpg",
  "DPDNL": "https://app.heyvoila.io/courier-service-logos/thumbnails/dpd-nl.jpg",
  "DttDeliveriesLtd": "https://app.heyvoila.io/courier-service-logos/thumbnails/dtt.jpg",
  "Dunelm": "https://app.heyvoila.io/courier-service-logos/thumbnails/dunelm.jpg",
  "DX": "https://app.heyvoila.io/courier-service-logos/thumbnails/dx.jpg",
  "DxExpress": "https://app.heyvoila.io/courier-service-logos/thumbnails/dx-express.jpg",
  "DxFreight": "https://app.heyvoila.io/courier-service-logos/thumbnails/dx-freight.jpg",
  "Envialia": "https://app.heyvoila.io/courier-service-logos/thumbnails/envialia.jpg",
  "ETADistribution": "https://app.heyvoila.io/courier-service-logos/thumbnails/eta.jpg",
  "Evri": "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "EvriCorporate": "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "EvriInternational": "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "Exelot": "https://app.heyvoila.io/courier-service-logos/thumbnails/exelot.jpg",
  "Exfreight": "https://app.heyvoila.io/courier-service-logos/thumbnails/exfreight.jpg",
  "ExpectDistribution": "https://app.heyvoila.io/courier-service-logos/thumbnails/expect.jpg",
  "ExpressLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/expresslogistics.jpg",
  "FastDespatchLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/fastdespatchlogistics.jpg",
  "Fastway": "https://app.heyvoila.io/courier-service-logos/thumbnails/fastway.jpg",
  "Fedex": "https://app.heyvoila.io/courier-service-logos/thumbnails/fedex.png",
  "P2P": "https://app.heyvoila.io/courier-service-logos/thumbnails/fedex.png",
  "FedexV2": "https://app.heyvoila.io/courier-service-logos/thumbnails/fedex.png",
  "FloStream": "https://app.heyvoila.io/courier-service-logos/thumbnails/flostream.jpg",
  "Fosseway": "https://app.heyvoila.io/courier-service-logos/thumbnails/fosseway.jpg",
  "Furdeco": "https://app.heyvoila.io/courier-service-logos/thumbnails/furdeco.jpg",
  "GFS": "https://app.heyvoila.io/courier-service-logos/thumbnails/gfs.jpg",
  "GlobalCorporateLogisticsLtd": "https://app.heyvoila.io/courier-service-logos/thumbnails/globalcorporatelogistics.jpg",
  "GlobalE": "https://app.heyvoila.io/courier-service-logos/thumbnails/global-e.jpg",
  "GLSFR": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls.jpg",
  "GLSDE": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls.jpg",
  "GLSIE": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls.jpg",
  "GLSNL": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls.jpg",
  "GLSPL": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls-pl.jpg",
  "GLSES": "https://app.heyvoila.io/courier-service-logos/thumbnails/gls.jpg",
  "HanciaLtd": "https://app.heyvoila.io/courier-service-logos/thumbnails/hancia.jpg",
  "Hermes": "https://app.heyvoila.io/courier-service-logos/thumbnails/hermes.jpg",
  "HermesCorporate": "https://app.heyvoila.io/courier-service-logos/thumbnails/hermes.jpg",
  "Hived": "https://app.heyvoila.io/courier-service-logos/thumbnails/hived.jpg",
  "HubEurope": "https://app.heyvoila.io/courier-service-logos/thumbnails/hubeurope.jpg",
  "HubEuropeExpress": "https://app.heyvoila.io/courier-service-logos/thumbnails/hubeurope.jpg",
  "HubooShipping": "https://app.heyvoila.io/courier-service-logos/thumbnails/huboo.jpg",
  "Huxloe": "https://app.heyvoila.io/courier-service-logos/thumbnails/huxloe.jpg",
  "ImpactExpress": "https://app.heyvoila.io/courier-service-logos/thumbnails/impact_express.jpg",
  "InPost": "https://app.heyvoila.io/courier-service-logos/thumbnails/InPost.jpg",
  "InternationalBridgeUSPS": "https://app.heyvoila.io/courier-service-logos/thumbnails/usps.jpg",
  "InXpressBelfast": "https://app.heyvoila.io/courier-service-logos/thumbnails/inxpressbelfast.jpg",
  "Landmark": "https://app.heyvoila.io/courier-service-logos/thumbnails/landmark.jpg",
  "Loco": "https://app.heyvoila.io/courier-service-logos/thumbnails/loco.jpg",
  "LowCostParcels": "https://app.heyvoila.io/courier-service-logos/thumbnails/lowcostparcels.jpg",
  "MH": "https://app.heyvoila.io/courier-service-logos/thumbnails/mh.jpg",
  "MHI": "https://app.heyvoila.io/courier-service-logos/thumbnails/mhi.jpg",
  "MoovParcel": "https://app.heyvoila.io/courier-service-logos/thumbnails/moov.jpg",
  "MushipLimited": "https://app.heyvoila.io/courier-service-logos/thumbnails/muship.jpg",
  "Norsk": "https://app.heyvoila.io/courier-service-logos/thumbnails/norsk.jpg",
  "NowFulfilment": "https://app.heyvoila.io/courier-service-logos/thumbnails/nowfulfilment.jpg",
  "OnLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/onlogistics.jpg",
  "OrangeDS": "https://app.heyvoila.io/courier-service-logos/thumbnails/orangeds.jpg",
  "Paack": "https://app.heyvoila.io/courier-service-logos/thumbnails/paack.jpg",
  "PalletTrack": "https://app.heyvoila.io/courier-service-logos/thumbnails/pallet_track.jpg",
  "Palletforce": "https://app.heyvoila.io/courier-service-logos/thumbnails/palletforce.jpg",
  "PalletWays": "https://app.heyvoila.io/courier-service-logos/thumbnails/palletways.jpg",
  "Pallex": "https://app.heyvoila.io/courier-service-logos/thumbnails/pallex.jpg",
  "PallexV2": "https://app.heyvoila.io/courier-service-logos/thumbnails/pallex.jpg",
  "ParcelDeliverySolutionsLtd": "https://app.heyvoila.io/courier-service-logos/thumbnails/parceldeliverysolutionsltd.jpg",
  "Parcel2Go": "https://app.heyvoila.io/courier-service-logos/thumbnails/parcel2go.jpg",
  "Parcelforce": "https://app.heyvoila.io/courier-service-logos/thumbnails/parcelforce.jpg",
  "ParcelGiantWorldwide": "https://app.heyvoila.io/courier-service-logos/thumbnails/parcel-giant.jpg",
  "ParcelHub": "https://app.heyvoila.io/courier-service-logos/thumbnails/parcelhub.jpg",
  "Parceltec": "https://app.heyvoila.io/courier-service-logos/thumbnails/parceltec.jpg",
  "PDCLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/pdc.jpg",
  "Polaris": "https://app.heyvoila.io/courier-service-logos/thumbnails/polaris.jpg",
  "PostNL": "https://app.heyvoila.io/courier-service-logos/thumbnails/postnl.jpg",
  "PPI": "https://app.heyvoila.io/courier-service-logos/thumbnails/ppi.jpg",
  "ProCarrier": "https://app.heyvoila.io/courier-service-logos/thumbnails/procarrier.jpg",
  "PTS": "https://app.heyvoila.io/courier-service-logos/thumbnails/pts.jpg",
  "Relay": "https://app.heyvoila.io/courier-service-logos/thumbnails/relay.jpg",
  "RMCDistributionUK": "https://app.heyvoila.io/courier-service-logos/thumbnails/rmc.jpg",
  "RoyalMail": "https://app.heyvoila.io/courier-service-logos/thumbnails/royalmail.jpg",
  "RoyalMailClickAndDrop": "https://app.heyvoila.io/courier-service-logos/thumbnails/royalmail_clickanddrop.jpg",
  "RoyalMailIntersoft": "https://app.heyvoila.io/courier-service-logos/thumbnails/royalmail_intersoft.jpg",
  "Rush": "https://app.heyvoila.io/courier-service-logos/thumbnails/rush.jpg",
  "Samos": "https://app.heyvoila.io/courier-service-logos/thumbnails/samos-ecommerce.jpg",
  "Seur": "https://app.heyvoila.io/courier-service-logos/thumbnails/seur.jpg",
  "SharkDistribution": "https://app.heyvoila.io/courier-service-logos/thumbnails/shark.jpg",
  "Shippr": "https://app.heyvoila.io/courier-service-logos/thumbnails/shippr.jpg",
  "SkyNet": "https://app.heyvoila.io/courier-service-logos/thumbnails/skynet.jpg",
  "SmartTrack": "https://app.heyvoila.io/courier-service-logos/thumbnails/smarttrack.jpg",
  "SpringGlobal": "https://app.heyvoila.io/courier-service-logos/thumbnails/spring.jpg",
  "SpringXBS": "https://app.heyvoila.io/courier-service-logos/thumbnails/spring.jpg",
  "StampsUSPS": "https://app.heyvoila.io/courier-service-logos/thumbnails/usps.jpg",
  "Starlinks": "https://app.heyvoila.io/courier-service-logos/thumbnails/starlinks.jpg",
  "Stuart": "https://app.heyvoila.io/courier-service-logos/thumbnails/stuart-logo.jpg",
  "Swap": "https://app.heyvoila.io/courier-service-logos/thumbnails/swap.jpg",
  "Teleship": "https://app.heyvoila.io/courier-service-logos/thumbnails/teleship.png",
  "Temu": "https://app.heyvoila.io/courier-service-logos/thumbnails/temu.jpg",
  "Test": "https://app.heyvoila.io/courier-service-logos/thumbnails/test.png",
  "SecuredMail": "https://app.heyvoila.io/courier-service-logos/thumbnails/securedmail.jpg",
  "ThePalletNetwork": "https://app.heyvoila.io/courier-service-logos/thumbnails/thepalletnetwork.jpg",
  "THG": "https://app.heyvoila.io/courier-service-logos/thumbnails/thg.jpg",
  "Tiari": "https://app.heyvoila.io/courier-service-logos/thumbnails/tiari.jpg",
  "TikTokShop": "https://app.heyvoila.io/courier-service-logos/thumbnails/tiktokshop.png",
  "Tipsacarrier": "https://app.heyvoila.io/courier-service-logos/thumbnails/tipsa.png",
  "TNT": "https://app.heyvoila.io/courier-service-logos/thumbnails/tnt.jpg",
  "TomsTransit": "https://app.heyvoila.io/courier-service-logos/thumbnails/toms_transit.jpg",
  "TotalFulfilment": "https://app.heyvoila.io/courier-service-logos/thumbnails/totalfulfilment.jpg",
  "TransforceBE": "https://app.heyvoila.io/courier-service-logos/thumbnails/transforce.jpg",
  "TransGlobal": "https://app.heyvoila.io/courier-service-logos/thumbnails/transglobal.jpg",
  "TransMission": "https://app.heyvoila.io/courier-service-logos/thumbnails/transmission.png",
  "TrunkrsNL": "https://app.heyvoila.io/courier-service-logos/thumbnails/trunkrs.jpg",
  "Tuffnells": "https://app.heyvoila.io/courier-service-logos/thumbnails/tuffnells.jpg",
  "UKMail": "https://app.heyvoila.io/courier-service-logos/thumbnails/ukmail.jpg",
  "UPN": "https://app.heyvoila.io/courier-service-logos/thumbnails/upn.jpg",
  "UPS": "https://app.heyvoila.io/courier-service-logos/thumbnails/ups.jpg",
  "UPSv2": "https://app.heyvoila.io/courier-service-logos/thumbnails/ups.jpg",
  "UrbIt": "https://app.heyvoila.io/courier-service-logos/thumbnails/urbit.jpg",
  "Vamox": "https://app.heyvoila.io/courier-service-logos/thumbnails/vamox.jpg",
  "Very": "https://app.heyvoila.io/courier-service-logos/thumbnails/very.jpg",
  "WLogistics": "https://app.heyvoila.io/courier-service-logos/thumbnails/wlogistics.jpg",
  "Wayfair": "https://app.heyvoila.io/courier-service-logos/thumbnails/wayfair.jpg",
  "Whistl": "https://app.heyvoila.io/courier-service-logos/thumbnails/whistl.jpg",
  "WorldwideShipping": "https://app.heyvoila.io/courier-service-logos/thumbnails/worldwideshipping.jpg",
  "XDP": "https://app.heyvoila.io/courier-service-logos/thumbnails/xdp.jpg",
  "Yodel": "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "YodelC2C": "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "YodelECR": "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "YodelLink": "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "YodelReturns": "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "YunExpress": "https://app.heyvoila.io/courier-service-logos/thumbnails/yunexpress.jpg",
  "YunExpressUSA": "https://app.heyvoila.io/courier-service-logos/thumbnails/yunexpress.jpg",
  "Zedify": "https://app.heyvoila.io/courier-service-logos/thumbnails/zedify.jpg",

  // ── Manual aliases ───────────────────────────────────────────────────────────
  // Evri / EvriCorporate — same logo, cover all spacing/casing variants
  "evricorporate":   "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "evri corporate":  "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "Evri Corporate":  "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",
  "evri":            "https://app.heyvoila.io/courier-service-logos/thumbnails/evri.jpg",

  // Yodel C2C — cover space-separated and lowercase variants
  "yodel c2c":       "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "Yodel C2C":       "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "yodelc2c":        "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
  "yodel c 2 c":     "https://app.heyvoila.io/courier-service-logos/thumbnails/yodel.jpg",
};

export function getCourierLogo(courierCode) {
  if (!courierCode) return null;
  const code = String(courierCode).trim();
  return COURIER_LOGOS[code] || COURIER_LOGOS[code.toLowerCase()] || null;
}
