export const COUNTRIES = [
  { iso: 'AD', name: 'Andorra' }, { iso: 'AE', name: 'United Arab Emirates' },
  { iso: 'AF', name: 'Afghanistan' }, { iso: 'AG', name: 'Antigua and Barbuda' },
  { iso: 'AI', name: 'Anguilla' }, { iso: 'AL', name: 'Albania' },
  { iso: 'AM', name: 'Armenia' }, { iso: 'AO', name: 'Angola' },
  { iso: 'AR', name: 'Argentina' }, { iso: 'AS', name: 'American Samoa' },
  { iso: 'AT', name: 'Austria' }, { iso: 'AU', name: 'Australia' },
  { iso: 'AW', name: 'Aruba' }, { iso: 'AZ', name: 'Azerbaijan' },
  { iso: 'BA', name: 'Bosnia and Herzegovina' }, { iso: 'BB', name: 'Barbados' },
  { iso: 'BD', name: 'Bangladesh' }, { iso: 'BE', name: 'Belgium' },
  { iso: 'BF', name: 'Burkina Faso' }, { iso: 'BG', name: 'Bulgaria' },
  { iso: 'BH', name: 'Bahrain' }, { iso: 'BI', name: 'Burundi' },
  { iso: 'BJ', name: 'Benin' }, { iso: 'BM', name: 'Bermuda' },
  { iso: 'BN', name: 'Brunei' }, { iso: 'BO', name: 'Bolivia' },
  { iso: 'BR', name: 'Brazil' }, { iso: 'BS', name: 'Bahamas' },
  { iso: 'BT', name: 'Bhutan' }, { iso: 'BW', name: 'Botswana' },
  { iso: 'BY', name: 'Belarus' }, { iso: 'BZ', name: 'Belize' },
  { iso: 'CA', name: 'Canada' }, { iso: 'CD', name: 'DR Congo' },
  { iso: 'CF', name: 'Central African Republic' }, { iso: 'CG', name: 'Republic of the Congo' },
  { iso: 'CH', name: 'Switzerland' }, { iso: 'CI', name: "Côte d'Ivoire" },
  { iso: 'CK', name: 'Cook Islands' }, { iso: 'CL', name: 'Chile' },
  { iso: 'CM', name: 'Cameroon' }, { iso: 'CN', name: 'China' },
  { iso: 'CO', name: 'Colombia' }, { iso: 'CR', name: 'Costa Rica' },
  { iso: 'CU', name: 'Cuba' }, { iso: 'CV', name: 'Cape Verde' },
  { iso: 'CW', name: 'Curaçao' }, { iso: 'CY', name: 'Cyprus' },
  { iso: 'CZ', name: 'Czech Republic' }, { iso: 'DE', name: 'Germany' },
  { iso: 'DJ', name: 'Djibouti' }, { iso: 'DK', name: 'Denmark' },
  { iso: 'DM', name: 'Dominica' }, { iso: 'DO', name: 'Dominican Republic' },
  { iso: 'DZ', name: 'Algeria' }, { iso: 'EC', name: 'Ecuador' },
  { iso: 'EE', name: 'Estonia' }, { iso: 'EG', name: 'Egypt' },
  { iso: 'ER', name: 'Eritrea' }, { iso: 'ES', name: 'Spain' },
  { iso: 'ET', name: 'Ethiopia' }, { iso: 'FI', name: 'Finland' },
  { iso: 'FJ', name: 'Fiji' }, { iso: 'FK', name: 'Falkland Islands' },
  { iso: 'FM', name: 'Micronesia' }, { iso: 'FO', name: 'Faroe Islands' },
  { iso: 'FR', name: 'France' }, { iso: 'GA', name: 'Gabon' },
  { iso: 'GB', name: 'United Kingdom' }, { iso: 'GD', name: 'Grenada' },
  { iso: 'GE', name: 'Georgia' }, { iso: 'GF', name: 'French Guiana' },
  { iso: 'GG', name: 'Guernsey' }, { iso: 'GH', name: 'Ghana' },
  { iso: 'GI', name: 'Gibraltar' }, { iso: 'GL', name: 'Greenland' },
  { iso: 'GM', name: 'Gambia' }, { iso: 'GN', name: 'Guinea' },
  { iso: 'GP', name: 'Guadeloupe' }, { iso: 'GQ', name: 'Equatorial Guinea' },
  { iso: 'GR', name: 'Greece' }, { iso: 'GT', name: 'Guatemala' },
  { iso: 'GU', name: 'Guam' }, { iso: 'GW', name: 'Guinea-Bissau' },
  { iso: 'GY', name: 'Guyana' }, { iso: 'HK', name: 'Hong Kong' },
  { iso: 'HN', name: 'Honduras' }, { iso: 'HR', name: 'Croatia' },
  { iso: 'HT', name: 'Haiti' }, { iso: 'HU', name: 'Hungary' },
  { iso: 'ID', name: 'Indonesia' }, { iso: 'IE', name: 'Ireland' },
  { iso: 'IL', name: 'Israel' }, { iso: 'IM', name: 'Isle of Man' },
  { iso: 'IN', name: 'India' }, { iso: 'IQ', name: 'Iraq' },
  { iso: 'IR', name: 'Iran' }, { iso: 'IS', name: 'Iceland' },
  { iso: 'IT', name: 'Italy' }, { iso: 'JE', name: 'Jersey' },
  { iso: 'JM', name: 'Jamaica' }, { iso: 'JO', name: 'Jordan' },
  { iso: 'JP', name: 'Japan' }, { iso: 'KE', name: 'Kenya' },
  { iso: 'KG', name: 'Kyrgyzstan' }, { iso: 'KH', name: 'Cambodia' },
  { iso: 'KI', name: 'Kiribati' }, { iso: 'KM', name: 'Comoros' },
  { iso: 'KN', name: 'Saint Kitts and Nevis' }, { iso: 'KP', name: 'North Korea' },
  { iso: 'KR', name: 'South Korea' }, { iso: 'KW', name: 'Kuwait' },
  { iso: 'KY', name: 'Cayman Islands' }, { iso: 'KZ', name: 'Kazakhstan' },
  { iso: 'LA', name: 'Laos' }, { iso: 'LB', name: 'Lebanon' },
  { iso: 'LC', name: 'Saint Lucia' }, { iso: 'LI', name: 'Liechtenstein' },
  { iso: 'LK', name: 'Sri Lanka' }, { iso: 'LR', name: 'Liberia' },
  { iso: 'LS', name: 'Lesotho' }, { iso: 'LT', name: 'Lithuania' },
  { iso: 'LU', name: 'Luxembourg' }, { iso: 'LV', name: 'Latvia' },
  { iso: 'LY', name: 'Libya' }, { iso: 'MA', name: 'Morocco' },
  { iso: 'MC', name: 'Monaco' }, { iso: 'MD', name: 'Moldova' },
  { iso: 'ME', name: 'Montenegro' }, { iso: 'MG', name: 'Madagascar' },
  { iso: 'MH', name: 'Marshall Islands' }, { iso: 'MK', name: 'North Macedonia' },
  { iso: 'ML', name: 'Mali' }, { iso: 'MM', name: 'Myanmar' },
  { iso: 'MN', name: 'Mongolia' }, { iso: 'MO', name: 'Macau' },
  { iso: 'MQ', name: 'Martinique' }, { iso: 'MR', name: 'Mauritania' },
  { iso: 'MS', name: 'Montserrat' }, { iso: 'MT', name: 'Malta' },
  { iso: 'MU', name: 'Mauritius' }, { iso: 'MV', name: 'Maldives' },
  { iso: 'MW', name: 'Malawi' }, { iso: 'MX', name: 'Mexico' },
  { iso: 'MY', name: 'Malaysia' }, { iso: 'MZ', name: 'Mozambique' },
  { iso: 'NA', name: 'Namibia' }, { iso: 'NC', name: 'New Caledonia' },
  { iso: 'NE', name: 'Niger' }, { iso: 'NG', name: 'Nigeria' },
  { iso: 'NI', name: 'Nicaragua' }, { iso: 'NL', name: 'Netherlands' },
  { iso: 'NO', name: 'Norway' }, { iso: 'NP', name: 'Nepal' },
  { iso: 'NR', name: 'Nauru' }, { iso: 'NZ', name: 'New Zealand' },
  { iso: 'OM', name: 'Oman' }, { iso: 'PA', name: 'Panama' },
  { iso: 'PE', name: 'Peru' }, { iso: 'PF', name: 'French Polynesia' },
  { iso: 'PG', name: 'Papua New Guinea' }, { iso: 'PH', name: 'Philippines' },
  { iso: 'PK', name: 'Pakistan' }, { iso: 'PL', name: 'Poland' },
  { iso: 'PR', name: 'Puerto Rico' }, { iso: 'PS', name: 'Palestine' },
  { iso: 'PT', name: 'Portugal' }, { iso: 'PW', name: 'Palau' },
  { iso: 'PY', name: 'Paraguay' }, { iso: 'QA', name: 'Qatar' },
  { iso: 'RE', name: 'Réunion' }, { iso: 'RO', name: 'Romania' },
  { iso: 'RS', name: 'Serbia' }, { iso: 'RU', name: 'Russia' },
  { iso: 'RW', name: 'Rwanda' }, { iso: 'SA', name: 'Saudi Arabia' },
  { iso: 'SB', name: 'Solomon Islands' }, { iso: 'SC', name: 'Seychelles' },
  { iso: 'SD', name: 'Sudan' }, { iso: 'SE', name: 'Sweden' },
  { iso: 'SG', name: 'Singapore' }, { iso: 'SH', name: 'Saint Helena' },
  { iso: 'SI', name: 'Slovenia' }, { iso: 'SK', name: 'Slovakia' },
  { iso: 'SL', name: 'Sierra Leone' }, { iso: 'SM', name: 'San Marino' },
  { iso: 'SN', name: 'Senegal' }, { iso: 'SO', name: 'Somalia' },
  { iso: 'SR', name: 'Suriname' }, { iso: 'SS', name: 'South Sudan' },
  { iso: 'ST', name: 'São Tomé and Príncipe' }, { iso: 'SV', name: 'El Salvador' },
  { iso: 'SY', name: 'Syria' }, { iso: 'SZ', name: 'Eswatini' },
  { iso: 'TC', name: 'Turks and Caicos Islands' }, { iso: 'TD', name: 'Chad' },
  { iso: 'TG', name: 'Togo' }, { iso: 'TH', name: 'Thailand' },
  { iso: 'TJ', name: 'Tajikistan' }, { iso: 'TL', name: 'Timor-Leste' },
  { iso: 'TM', name: 'Turkmenistan' }, { iso: 'TN', name: 'Tunisia' },
  { iso: 'TR', name: 'Turkey' }, { iso: 'TT', name: 'Trinidad and Tobago' },
  { iso: 'TV', name: 'Tuvalu' }, { iso: 'TW', name: 'Taiwan' },
  { iso: 'TZ', name: 'Tanzania' }, { iso: 'UA', name: 'Ukraine' },
  { iso: 'UG', name: 'Uganda' }, { iso: 'US', name: 'United States' },
  { iso: 'UY', name: 'Uruguay' }, { iso: 'UZ', name: 'Uzbekistan' },
  { iso: 'VA', name: 'Vatican City' }, { iso: 'VC', name: 'Saint Vincent and the Grenadines' },
  { iso: 'VE', name: 'Venezuela' }, { iso: 'VG', name: 'British Virgin Islands' },
  { iso: 'VI', name: 'US Virgin Islands' }, { iso: 'VN', name: 'Vietnam' },
  { iso: 'VU', name: 'Vanuatu' }, { iso: 'WS', name: 'Samoa' },
  { iso: 'XK', name: 'Kosovo' }, { iso: 'YE', name: 'Yemen' },
  { iso: 'YT', name: 'Mayotte' }, { iso: 'ZA', name: 'South Africa' },
  { iso: 'ZM', name: 'Zambia' }, { iso: 'ZW', name: 'Zimbabwe' },
];

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.iso, c.name]));
export const getCountryName = iso => COUNTRY_MAP[iso] || iso;
